# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GIOimport
                                 A QGIS plugin
 Imports Omgevingswet GIO's in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-05-21
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Marco Duiker - LandGoed
        email                : marco.duiker@landgoed.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QUrl
from qgis.PyQt.QtGui import QIcon, QDesktopServices
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QProgressBar, \
                                QApplication, QMessageBox
from qgis.core import Qgis, QgsMessageLog, QgsProject, QgsApplication, \
                      QgsVectorLayer, QgsLayerDefinition, QgsLayerTreeLayer, \
                      QgsMapLayerProxyModel

import lxml
from lxml import etree

import mmap
import shutil


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .gio_import_dialog import GIOimportDialog
import os.path


NAMED_LAYER_WRAPPER = '''
<NamedLayer>
    <se:Name>%s</se:Name>
    <UserStyle>
      <se:Name>%s</se:Name>
      %s
    </UserStyle>
</NamedLayer>
'''

SLD_FILE_WRAPPER = '''<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor  xmlns="http://www.opengis.net/sld" 
                        xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd" 
                        xmlns:xlink="http://www.w3.org/1999/xlink" 
                        xmlns:se="http://www.opengis.net/se" 
                        xmlns:ogc="http://www.opengis.net/ogc" 
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        version="1.1.0" >
%s
</StyledLayerDescriptor>
''' % NAMED_LAYER_WRAPPER


class GIOimport:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GIO import plugin')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GIOimport', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/gio_import/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'GIO import'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&GIO import plugin'),
                action)
            self.iface.removeToolBarIcon(action)


    def chooseFile(self):
        """Reacts on browse button and opens the right file selector dialog"""

        fileNames = QFileDialog.getOpenFileNames(
             caption = self.tr(u"Select GIO .gml and/ or .xml file(s)"), 
             directory = '', 
             filter = '*.gml *.xml')
        self.fileNames = ';'.join(fileNames[0])
        self.dlg.fileNameBox.setText(self.fileNames)

    def showHelp(self):
        """Reacts on help button"""

        #qgis.utils.showPluginHelp(filename = 'help/index')
        QDesktopServices().openUrl(QUrl.fromLocalFile( \
            os.path.join("file://", self.plugin_dir, 'help/build/html', \
                         'index.html')))


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when 
        # the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GIOimportDialog()

            # define some connections
            self.dlg.fileBrowseButton.clicked.connect(self.chooseFile)
            self.dlg.helpButton.clicked.connect(self.showHelp)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            
            try:
                file_names_list = self.fileNames.split(';')
                number_of_files = len(file_names_list)
                if not number_of_files:
                    raise Exception()
            except:
                self.iface.messageBar().pushMessage("Error",
                    self.tr(u'Select at least one file to import.'), 
                            level = Qgis.Critical)    
                return

            # set up some user communication
            QApplication.setOverrideCursor(QtCore.Qt.WaitCursor)

            self.iface.messageBar().pushMessage("Info",
                self.tr(u'Start') + ' ' + self.tr(u'Importing GIO files ...'))
            progressMessageBar = self.iface.messageBar().createMessage( \
                self.tr(u'Importing GIO files ...'))
            bar = QProgressBar()
            bar.setRange(0,0)
            bar.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
            progressMessageBar.layout().addWidget(bar)
            self.iface.messageBar().pushWidget(progressMessageBar, Qgis.Info)

            count = 0
            self.results = {}
            for file_name in file_names_list:
                count = count + 1
                sld = None
                if file_name[-4:] == '.xml':
                    try:
                        doc  = etree.parse(file_name)
                        file_base_name = doc.xpath(
                                ".//*[local-name() = 'bestandsnaam']")[0].text
                        file_name = os.path.join(os.path.dirname(file_name), 
                                                 file_base_name)
                    except:
                        self.iface.messageBar().pushMessage(
                            "Error",
                            "%s: %s" % (self.tr(u'Could not find gml file name in'), 
                                        os.path.basename(file_name)), 
                            level = Qgis.Warning)
                        continue
                    sld = doc.xpath(".//*[local-name() = 'FeatureTypeStyle']")
                    if sld:
                        # we support only 1 style
                        sld = sld[0]

                progressMessageBar.setText(self.tr(u"Analyzing file ") + \
                    str(count) + self.tr(u" from ") + str(number_of_files) + \
                    ": " + os.path.basename(file_name))

                style_file = None
                with open(file_name, 'rb', 0) as file, \
                    mmap.mmap(file.fileno(), 0, access=mmap.ACCESS_READ) as s:
                    if s.find(b'posList') != -1:
                        if s.find(b'urface') != -1:
                            gfs_type = 'Surface'
                        elif s.find(b'olygon') != -1:
                            gfs_type = 'Surface'
                        else:
                            gfs_type = 'Curve'
                    else:
                        gfs_type = 'Point'
                    
                shutil.copy(os.path.join(
                                self.plugin_dir,
                                'resources','gfs', 'gio-gml-%s.gfs' % gfs_type),
                            '%s.gfs' % file_name[:-4])
      
                progressMessageBar.setText(
                    self.tr(u"Adding file ") + str(count) + self.tr(u" from ") + \
                    str(number_of_files) + ": " + os.path.basename(file_name))

                vlayer = None
                try:
                    vlayer = self.iface.addVectorLayer(
                            file_name,os.path.basename(file_name)[:-4],'ogr')
                except:
                    self.iface.messageBar().pushMessage(
                        "Error",
                        "%s: %s" %(self.tr(u'Failed to import'),
                                        os.path.basename(file_name)), 
                        level = Qgis.Warning) 
                    QgsMessageLog.logMessage(self.tr(u'Failed to import') + \
                                str(os.path.basename(file_name)), 'GIOImport')
                    QApplication.restoreOverrideCursor()

                if vlayer:
                    if sld:
                        # we kunnen sld uit een string toepassen door eerst 
                        # de featuretypestyle in te lezen uit de GIO
                        # https://gis.stackexchange.com/questions/223912/read-sld-style-in-pyqgis
                        # lukt niet, dus nu maar de SLD wegsaven
                        sld_file = file_name[:-4] + '.sld'  
                        sld_string = SLD_FILE_WRAPPER % (os.path.basename(file_name),
                                                         os.path.basename(file_name),
                                                         etree.tostring(sld).decode("utf-8"))
                        try:
                            with open(sld_file,'w') as f:
                                f.write(sld_string)
                        except Exception as v:
                            self.iface.messageBar().pushMessage(
                                "Error",
                                "%s: %s" %(self.tr(u'Failed to write style file %s'),
                                                os.path.basename(sld_file)), 
                                level = Qgis.Warning)
                    else:
                        sld_file = os.path.join(
                                        self.plugin_dir,
                                        'resources','sld','%s.sld' % 'default')
                    error, succes = vlayer.loadSldStyle(sld_file)
                    if error: 
                        QgsMessageLog.logMessage(self.tr(u'Error loading style: ') + \
                                                 str(result), 'GIOImport')


            # finish the user communication
            QApplication.restoreOverrideCursor()

            progressMessageBar.setText(self.tr(u"Importing GIO files done!"))
            bar.setRange(0,100)
            bar.setValue(100)



